# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ACCOUNTS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professordetail',
            name='user',
        ),
        migrations.AddField(
            model_name='professordetail',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
