# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 02:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignmentdetail',
            name='CreationDate',
            field=models.DateField(default=datetime.date(2017, 7, 1)),
        ),
    ]
