# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 09:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0002_auto_20161020_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AS_ID', models.CharField(max_length=20, null=True)),
                ('Creation_Date', models.CharField(max_length=20)),
                ('StartDate', models.DateTimeField(verbose_name='date published')),
                ('EndDate', models.DateTimeField(verbose_name='date published')),
                ('Course_id', models.CharField(max_length=20)),
                ('Description', models.TextField(max_length=200)),
                ('Language', models.TextField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='professordetail',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
