# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0003_auto_20161024_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='EndDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='StartDate',
            field=models.DateTimeField(),
        ),
    ]
