# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-25 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0004_auto_20161024_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=20)),
                ('CourseId', models.CharField(max_length=20)),
                ('Description', models.TextField(max_length=200)),
                ('PId', models.CharField(max_length=20)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateField()),
                ('Semester', models.IntegerField()),
                ('Year', models.CharField(max_length=4)),
            ],
        ),
    ]
