# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0007_auto_20161027_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetail',
            name='EndDate',
        ),
    ]
