# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0008_remove_coursedetail_enddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='AS_ID',
            new_name='AssignmentID',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='Course_id',
            new_name='Courseid',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='Creation_Date',
            new_name='CreationDate',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='EndDate',
            new_name='EndTime',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='StartDate',
            new_name='StartTime',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='StartDate',
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='EndTime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='StartTime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='Language',
            field=models.CharField(max_length=20),
        ),
    ]
