# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0010_auto_20161027_0331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='AssignmentDetail',
        ),
    ]
