# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-29 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0011_auto_20161027_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetail',
            old_name='EndTime',
            new_name='EndDate',
        ),
        migrations.RenameField(
            model_name='coursedetail',
            old_name='StartTime',
            new_name='StartDate',
        ),
    ]
