# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0012_auto_20161030_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondetail',
            name='Output1',
        ),
        migrations.RemoveField(
            model_name='questiondetail',
            name='Output2',
        ),
        migrations.RemoveField(
            model_name='questiondetail',
            name='TestCaseInput1',
        ),
        migrations.RemoveField(
            model_name='questiondetail',
            name='TestCaseInput2',
        ),
    ]
