# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0014_questiondetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondetail',
            name='TestCaseInputFile1',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
