# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0015_questiondetail_testcaseinputfile1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondetail',
            name='Image',
        ),
    ]
