# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-02 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ACCOUNTS', '0017_assistantdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification', models.TextField(max_length=20)),
                ('Interests', models.TextField(blank='False', max_length=200)),
                ('SiD', models.CharField(max_length=20)),
                ('Batch', models.CharField(max_length=20)),
                ('Branch', models.CharField(max_length=20)),
                ('Programme', models.CharField(max_length=20)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
