# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-04 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0019_auto_20161103_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondetail',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
