# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qid', models.CharField(max_length=20)),
                ('Question', models.TextField(max_length=200)),
            ],
        ),
    ]
