# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-14 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qid', models.CharField(max_length=20)),
                ('QName', models.CharField(max_length=20)),
                ('QAuthor', models.CharField(max_length=20)),
                ('QDescription', models.CharField(max_length=20)),
                ('TestCaseInput1', models.TextField(blank='False', max_length=200)),
                ('TestCaseInput2', models.TextField(blank='False', max_length=200)),
                ('Output1', models.TextField(blank='False', max_length=100)),
                ('Output2', models.TextField(blank='False', max_length=100)),
                ('Question', models.TextField(max_length=200)),
            ],
        ),
    ]
